apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kahare/backend_app:v1.1.2
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 5000
            tty: true 
          stdin: true
          env:
            - name: REACT_APP_API_URL
              value: http://yolo-db-service:80
