apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: kahare/client_app:v1.1.2
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: client-volume
          mountPath: /var/www/client
      volumes:
      - name: client-volume
        hostPath:
          path: ./client
