apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - name: client-app
          image: kahare/client_app:v1.1.2
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://server-backend-service:80

