---

#Cloning repo  
- name: Clone Repository
  git:
    repo: 
    dest: "/var/www/backend"

#Configuring the containers 
- name: Build & start backend container 
  docker_container:
     name:  
     image: "{{ backend_image }}"
     state: started 
     restart_policy: always 
     ports: 
       - "5000:5000"
     volumes: 
       - /var/www/backend:/var/www/backend
     networks:
        - name: service_net #confirm this 
     env:
      MONGODB_URL: "mongodb://yolo_db:27018"
      DB_NAME:  #change this
